# Generated by Django 3.2.8 on 2021-12-25 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(default='unknown ip', max_length=80)),
                ('submit', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(default='', upload_to='parsers/')),
                ('parsing_completed', models.BooleanField(default=False)),
                ('parsing_result', models.TextField(default='no result')),
            ],
        ),
    ]
