# Generated by Django 3.2.8 on 2022-01-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodtest',
            old_name='pdf_file',
            new_name='client_file',
        ),
    ]
