# Generated by Django 3.2.8 on 2022-01-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bloodtest_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='table_found',
            field=models.BooleanField(default=False),
        ),
    ]
