# Generated by Django 3.2.8 on 2022-01-06 15:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bloodtest_table_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='client_file',
            field=models.FileField(default='', upload_to=api.models.get_filename),
        ),
    ]
