# Generated by Django 3.2.8 on 2022-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bloodtest_client_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='laboratory',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='bloodtest',
            name='table_formatted',
            field=models.BooleanField(default=False),
        ),
    ]
